#!/bin/bash
CWD="`pwd`";

ssh -o StrictHostKeyChecking=no dh2026pc00 < /dev/null "pkill -f SimpleProxyServer" &

for host in `cat hosts`
do
	echo $host
	ssh -o StrictHostKeyChecking=no $host < /dev/null "pkill -f watcher;" &
	ssh -o StrictHostKeyChecking=no $host < /dev/null "pkill -f URLShortner;" &
done
